language: generic
os: osx
osx_image: xcode6.4
env:
  matrix:
  - CONDA_PY=36
  global:
  - secure: RJA3QOIHU2cyLixvnY33F8WKAJ16rhaDFXM6T5sqiw4KebMBStKSaCUvDZS9o2NPMJvvChapcz07wvHirDTHRlr5sKylfyRRvq3H2B/Sbr2lgaYNmNHL6FySbl8uzYnwu9PrZ+dtL0qHf8jE7wGzFdVmnTczzf5sRK+uRZP8n6Cby27cdD2Ce92eqVrdLLLfGnk1/DLpswNtkaoqCkoAttyOGDFYlhSwOIqo8xkLcakj5vLI+bmjw/GmRWaK0v5xygIQn0JzqYx2jzv2t27phIFSDbLBYfwUjmG6xFFwOrMtw+ROhWez4jVSApWBOihguvBnZ5jA55BoOT7M+Nb8iinKEjaeshdFN7UTRFpafJZAN7aXfa6Ni+S0hWpLzgBQomCjYSFr6tRntuuG/0p6gGNikf4tcUd+RssexwVGuL4iohPrWrR1f1IKiNWj5aHTC6PE2bMGbSh6m2UJZaRGdFenQvPY2kl6ikVlsKcD4fI19U+WYBbiZZ65SMTcoQkb3vCkLiGJmaB6Vunv2/8MFIMNVpU+Vf/Bmac1LDVdFyfX+MneDSEBSbMSNvsCrck63KPPrZpxK2NF0tcW6GlNTQhQTlTrHOKj2XdbCQrg874jrVWzgx3U9h0JYVgePqinNMk6LBwYdGHVZw+4la8Zuz6pDBhVKqiNEyokE6CU74s=
before_install:
- |
  (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
      python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
- |
  echo ""
  echo "Removing homebrew from Travis CI to avoid conflicts."
  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
  chmod +x ~/uninstall_homebrew
  ~/uninstall_homebrew -fq
  rm ~/uninstall_homebrew
install:
- |
  echo ""
  echo "Installing a fresh version of Miniconda."
  MINICONDA_URL="https://repo.continuum.io/miniconda"
  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
  curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
  bash $MINICONDA_FILE -b
- |
  echo ""
  echo "Configuring conda."
  source /Users/travis/miniconda3/bin/activate root
  conda config --remove channels defaults
  conda config --add channels defaults
  conda config --add channels conda-forge
  conda config --add channels gouarin
  conda config --set show_channel_urls true
  conda install --yes --quiet conda-forge-build-setup
  source run_conda_forge_build_setup
script:
- conda build ./recipe
- upload_or_check_non_existence ./recipe gouarin --channel=main
